language: c
script: ./configure --disable-nls --enable-ssl $OPTIONAL_CONF_ARGS && make -j $(nproc)
compiler:
  - gcc
  - clang
matrix:
  fast_finish: true
  allow_failures:
    - env: OPTIONAL_CONF_ARGS="--with-contrib"
env:
  - OPTIONAL_CONF_ARGS=""
  - OPTIONAL_CONF_ARGS="--with-perl"
  - OPTIONAL_CONF_ARGS="--with-contrib"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y libperl-dev
